### PR TITLE
In RBAC included user administration and showed idea assigning roles in User Update screen

### PR DESCRIPTION
**Pull request by uldisn**

### CODE REVIEW

**Comment by dmeroff** [comment]
Thank you for contribution, but I'll not merge this, because it just duplicates yii2-user functionality.

Purpose of Yii2-rbac is to provide interface where user can perform CRUD operations on roles and permissions. It also provides special widget which can be added to your user edit form (yii2-user already uses it). Yii2-rbac shouldn't have any CRUD for users.

**Comment by uldisn** [comment]
You are right, but is one problem. Currently in Yii2-user acces control is without rbac, but, when implemented RBAC. Good practice is for user administration  give access for special role user_admin.

**Comment by dmeroff** [comment]
Yeah, I thought about that.

**Comment by uldisn** [comment]
I try in yii2-rbac use extended yii2-user admin controller. Views also try use from yii2-user, but do some changes.

**Comment by dmeroff** [comment]
You don't need to extend any classes from yii2-user and use them in yii2-rbac. It shouldn't work in this way.

Yii2-user already adopted to work with yii2-rbac, it has special form where you can set roles for user. Just upgrade your yii2-user version to the latest one.

**Pull request closed without merging**
